*** browser.prg
** aktion in suchen ( archiv_p.prg )

sele browser

append blank

repl neuwert with recno("kartei"), ben with kartei->ben, codewort with kartei->codewort, lfdnr with kartei->lfdnr, spezinr with kartei->spezinr, hst with kartei->hst, bes with kartei->bes, klassi with kartei->klassi, merkmale with kartei->merkmale, abw with kartei->abw, geraete_nr with kartei->geraete_nr, erst_eins with kartei->erst_eins, p_zeit with kartei->p_zeit, kfr with kartei->kfr, sonstiges with kartei->sonstiges, pb_art with kartei->pb_art, pb_datum with kartei->pb_datum, pb_kost with kartei->pb_kost, pb_ort with kartei->pb_ort, pb_bem with kartei->pb_bem

sele kartei